version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      - MYSQL_USER=daboggg
      - MYSQL_PASSWORD=624110
      - MYSQL_DATABASE=mondiv
      - MYSQL_ROOT_PASSWORD=144911
volumes:
  mysql_data: