# Generated by Django 3.2.6 on 2022-12-30 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Брокерский счет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ticker', models.CharField(max_length=8, unique=True, verbose_name='Тикер')),
                ('description', models.CharField(max_length=3000, verbose_name='О компании')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('icon_image', models.ImageField(null=True, upload_to='images/icon', verbose_name='Иконка')),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Вылюты',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField(verbose_name='Дата получения выплаты')),
                ('amount_of_shares', models.SmallIntegerField(verbose_name='Количество акций')),
                ('quantity_per_share', models.FloatField(verbose_name='Выплата на акцию')),
                ('pay_off', models.FloatField(blank=True, null=True, verbose_name='Выплата')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.account', verbose_name='Счет')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дивиденд',
                'verbose_name_plural': 'Дивиденды',
            },
        ),
    ]
