# Generated by Django 3.2.6 on 2022-12-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mondiv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
