# Generated by Django 3.2.6 on 2022-12-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondiv', '0002_remove_dividend_pay_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='payoff',
            field=models.FloatField(default=0, verbose_name='Выплата'),
        ),
    ]
