# Generated by Django 3.2.6 on 2022-12-05 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mondiv', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Валюта')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец счета'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField(verbose_name='Дата получения выплаты')),
                ('amount_of_shares', models.SmallIntegerField(verbose_name='Количество акций')),
                ('quantity_per_share', models.FloatField(verbose_name='Выплата на акцию')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.account', verbose_name='Счет')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дивиденд',
                'verbose_name_plural': 'Дивиденды',
            },
        ),
    ]
