# Generated by Django 3.2.6 on 2022-12-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondiv', '0003_dividend_payoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='payoff',
            field=models.FloatField(verbose_name='Выплата'),
        ),
    ]
