# Generated by Django 3.2.6 on 2022-12-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mondiv', '0004_alter_dividend_payoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='amount_of_shares',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='quantity_per_share',
        ),
    ]
