# Generated by Django 3.2.6 on 2022-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondiv', '0004_auto_20221205_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Вылюты'},
        ),
        migrations.AddField(
            model_name='dividend',
            name='payment',
            field=models.FloatField(blank=True, null=True, verbose_name='Выплата'),
        ),
        migrations.AlterField(
            model_name='company',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
