# Generated by Django 3.2.6 on 2023-01-06 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mondiv', '0005_auto_20221231_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mondiv.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
